#this script builds images and deploys to ECR

#this script does not deliver frontend and static files to S3
#to do so:
#run dev frontend Docker container, then: vite build --emptyOutDir -- --env=prod
#run dev Django container, then: python manage.py collectstatic --settings=voicewake.settings.prod

#at VSCode, open new Git Bash terminal
#then type: "sh thisfile.sh"

#old problem:
    #everything was labelled "latest", disallowing old & new from existing together in ECR
#solution:
    #inject some UUID generated by Git into Github Actions env, use it in naming
    #push to ECR once only, without differentiating stage/prod, since there's no need, and won't produce conflict with live prod containers
#https://tldp.org/LDP/abs/html/comparison-ops.html

#use nounset option to always exit bash if an env var does not exist
set -u

#theory:
#no .env needed if just building containers
#at dev, containers will have env_file specified to import env vars from .env
#at github action dev test, will import from secrets/vars, no .env option
#at AWS stage/prod, will point and use stage.env and prod.env

#create session
aws ecr get-login-password --region "${AWS_ECR_REGION_NAME}" | docker login --username AWS --password-stdin "${AWS_ECR_ACCOUNT_ID}.dkr.ecr.${AWS_ECR_REGION_NAME}.amazonaws.com"

#build all services from docker-compose-stage-prod.yaml
docker-compose --file docker-compose-stage-prod.yaml up -d --no-deps --force-recreate --no-start --build

#tag freshly built images with ECR tags
docker tag "vw-django_celery_beat:${GIT_PR_NUMBER}" "${AWS_ECR_ACCOUNT_ID}.dkr.ecr.${AWS_ECR_REGION_NAME}.amazonaws.com/vw-django_celery_beat:${GIT_PR_NUMBER}"
docker tag "vw-django_celery_worker:${GIT_PR_NUMBER}" "${AWS_ECR_ACCOUNT_ID}.dkr.ecr.${AWS_ECR_REGION_NAME}.amazonaws.com/vw-django_celery_worker:${GIT_PR_NUMBER}"
docker tag "vw-django_gunicorn:${GIT_PR_NUMBER}" "${AWS_ECR_ACCOUNT_ID}.dkr.ecr.${AWS_ECR_REGION_NAME}.amazonaws.com/vw-django_gunicorn:${GIT_PR_NUMBER}"
docker tag "vw-nginx:${GIT_PR_NUMBER}" "${AWS_ECR_ACCOUNT_ID}.dkr.ecr.${AWS_ECR_REGION_NAME}.amazonaws.com/vw-nginx:${GIT_PR_NUMBER}"

#push to AWS ECR
docker push "${AWS_ECR_ACCOUNT_ID}.dkr.ecr.${AWS_ECR_REGION_NAME}.amazonaws.com/vw-django_celery_beat:${GIT_PR_NUMBER}"
docker push "${AWS_ECR_ACCOUNT_ID}.dkr.ecr.${AWS_ECR_REGION_NAME}.amazonaws.com/vw-django_celery_worker:${GIT_PR_NUMBER}"
docker push "${AWS_ECR_ACCOUNT_ID}.dkr.ecr.${AWS_ECR_REGION_NAME}.amazonaws.com/vw-django_gunicorn:${GIT_PR_NUMBER}"
docker push "${AWS_ECR_ACCOUNT_ID}.dkr.ecr.${AWS_ECR_REGION_NAME}.amazonaws.com/vw-nginx:${GIT_PR_NUMBER}"