#in compose.yaml, things such as "command" and "entrypoint" will override things like CMD and ENTRYPOINT at .dockerfile
  #therefore, it's best to resort to .dockerfile and entrypoint.sh before placing such things here
#.dockerignore is expected to be at root directory of build context, i.e. where you are running "docker build" from
name: vw_dev
services:
  postgres:
    image: postgres:latest
    platform: "linux/amd64"
    ports:
      #using 5432+n for host port (left) in case you already have 5432 occupied by direct postgres installation on localhost machine
      - "5433:5432"
    expose:
      - "5433"
    #env_file is only used and seen by the container being run, not during docker compose
    #to use .env file and fill it in here during docker compose: "docker-compose --env-file ./env/.env up -d"
      #--env-file must come before "up", else "unknown flag" error
    env_file:
      - ./env/.env
    environment:
      #postgres image will auto-create an empty database using POSTGRES_DB when image is first started
      #to connect via pgAdmin: host (localhost), port (host port, i.e. 5433), maintenance database (voicewake), username (DB_USER), passwod (DB_PASSWORD)
      #removing server at pgAdmin only removes it from the list, i.e. not actual database deletion
      #for fresh start, "docker container ls -a", "docker container rm container_id", rebuild container, makemigrations, paste custom migration, migrate
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    #healthcheck seems to be required if you want other services to check it for "service_healthy" condition, else "dependency failed" error
    restart: unless-stopped
    healthcheck:
      #must test with POSTGRES_DB and POSTGRES_USER, else it will try to use "root" and get "role 'root' does not exist"
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - backend

  redis:
    working_dir: /redis
    image: redis:latest
    #if always restart, then when a service has error/ends, it will restart again
    # restart: always
    platform: "linux/amd64"
    ports:
      - "6379:6379"
    # volumes:
      # - /path/to/local/dаta:/root/redis
      # - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    healthcheck:
      #even when loading, Redis can still return exit code 0, so to be sure it's ready, expect "PONG"
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - backend

  django_runserver:
    tty: true
    build:
      context: .
      dockerfile: ./voicewake/docker/service-django-runserver.dockerfile
    volumes:
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
      - type: bind
        source: ./django_runserver.py
        target: /django_runserver.py
    restart: unless-stopped
    env_file:
      - /env/.env
    platform: "linux/amd64"
    ports:
      #map port on host to port on container
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
    #no need healthcheck for runserver if we have django_runserver.py

  django_gunicorn:
    tty: true
    build:
      #. because it relies on files like manage.py
      context: .
      dockerfile: ./voicewake/docker/service-gunicorn.dockerfile
    volumes:
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
    # restart: always
    env_file:
      - /env/.env
    platform: "linux/amd64"
    ports:
      #map port on host to port on container
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://127.0.0.1:5000 || exit 1
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - backend

  django_celery_worker:
    build:
      #. because it relies on files like manage.py
      context: .
      dockerfile: ./voicewake/docker/service-celery-worker.dockerfile
    volumes:
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
    # restart: always
    env_file:
      - /env/.env
    platform: "linux/amd64"
    ports:
      #this can be anything, since communication with django is using redis as broker via settings.CELERY_BROKER_URL
      - "8001:8001"
    depends_on:
      django_runserver:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: celery -A voicewake status || exit 1
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - backend

  django_celery_beat:
    build:
      #. because it relies on files like manage.py
      context: .
      dockerfile: ./voicewake/docker/service-celery-beat.dockerfile
    volumes:
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
    # restart: always
    env_file:
      - /env/.env
    platform: "linux/amd64"
    ports:
      #this can be anything, since communication with django is using redis as broker via settings.CELERY_BROKER_URL
      - "8002:8002"
    depends_on:
      django_runserver:
        condition: service_healthy
      django_celery_worker:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: python manage.py shell -c "from voicewake.services import do_celery_beat_healthcheck; do_celery_beat_healthcheck();"
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 80s
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    env_file:
      - ./env/.env
      #expecting env vars at runtime: DJANGO_SERVICE_NAME, DJANGO_PORT, FAVICON_URL
    platform: "linux/amd64"
    ports:
      - "8080:8080"
    volumes:
      #Gunicorn will not serve /static/, so NGINX must do it directly
      #perhaps we bind these dependency files so we don't have to download at host
      #and we can edit code from inside container for VSCode plugins to work
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./nginx/default.conf.template
        target: /etc/nginx/templates/default.conf.template
    depends_on:
      django_runserver:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      #NGINX will also fail if any upstream isn't responding, i.e. Django
      #force exit 1 if nginx status fails
      test: service nginx status || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    command: nginx-debug -g 'daemon off;'

  frontend:
    env_file:
      - ./env/.env
    build:
      context: .  #. because it relies on ./static
      dockerfile: ./frontend/Dockerfile
      #pass args for .dockerfile to use via ${ENV_NAME}
      args:
        VITE_PORT: ${VITE_PORT}
    volumes:
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./frontend
        target: /frontend
      # - type: bind
      #   source: ./voicewake
      #   target: /voicewake
      # - type: bind
      #   source: ./tailwind.config.js
      #   target: /tailwind.config.js
      #in container, specify the folder we want to ignore from bind-mount
      - /frontend/node_modules
    platform: "linux/amd64"
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    environment: 
      #allows for hot reload for JS dev, e.g. Vue/React/etc.
      #hot reload will not work without it
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped

  tailwind:
    #must use tty
      #provide pseudo-terminal, since we have -i flag, i.e. input
      #can see when watcher finishes applying new changes
      #keeps container alive
    tty: true
    build:
      context: .
      dockerfile: ./service-tailwind.dockerfile
    platform: "linux/amd64"
    ports:
      - "3000:3000"
    #we use bind mount between host files and container files for two-way sync
    volumes:
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
      - type: bind
        source: ./frontend
        target: /frontend
      - type: bind
        source: ./tailwind.config.js
        target: /tailwind.config.js
      #in container, specify the folder we want to ignore from bind-mount
      - /frontend/node_modules
    restart: unless-stopped

  #empty container to update packages, and allows for testing of installation itself
  update_npm:
    build:
      context: .
      dockerfile: ./service-update-npm.dockerfile
    #no volume binding, only copy files directly to host machine once satisfied

  #empty container to update packages, and allows for testing of installation itself
  update_pip:
    build:
      context: .
      dockerfile: ./service-update-pip.dockerfile
    #no volume binding, only copy files directly to host machine once satisfied

  #empty container to download and compile packages for air-gapped AWS Linux 2023
  aws_linux:
    image: amazonlinux:latest
    tty: true
    platform: "linux/amd64"
    ports:
      - "6677:6677"
    volumes:
      - type: bind
        source: ./ec2-setup-without-nat/local-create-offline-repo.sh
        target: /local-create-offline-repo.sh

volumes:
  static:
    #leave empty to use the container engine's default configuration for creating a volume
networks:
  backend:
    #this driver (bridge) is default when not explicitly defined here
    driver: bridge



