#in compose.yaml, things such as "command" and "entrypoint" will override things like CMD and ENTRYPOINT at .dockerfile
  #therefore, it's best to resort to .dockerfile and entrypoint.sh before placing such things here
services:
  test_service:
    build:
      context: .  #. because it relies on ./static
      dockerfile: ./test_service.dockerfile
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    #env_file is only used and seen by the container being run, not during docker compose
    #to use .env file and fill it in here during docker compose: "docker-compose --env-file ./env/.env up -d"
      #--env-file must come before "up", else "unknown flag" error
    env_file:
      - ./env/.env
    environment:
      #these are presumably only for setup
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    #healthcheck seems to be required if you want other services to check it for "service_healthy" condition, else "dependency failed" error
    healthcheck:
      #must test with POSTGRES_DB and POSTGRES_USER, else it will try to use "root" and get "role 'root' does not exist"
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - backend
  redis:
    working_dir: /redis
    image: redis:latest
    #if always restart, then when a service has error/ends, it will restart again
    # restart: always
    ports:
      - "6379:6379"
    # volumes:
      # - /path/to/local/dаta:/root/redis
      # - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=somepassword
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    #even when loading, Redis can still return exit code 0, so to be sure it's ready, expect "PONG"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 2s
      timeout: 3s
      retries: 5
    networks:
      - backend
  django_runserver:
    build:
      #context path dictates what "." points to in Dockerfile
      context: . #. because it relies on files like manage.py
      #dockerfile is relative to context path, and "../" can be used to reach context path's parent folder
      #seems like specifying until Dockerfile itself is needed, else "is a directory" error if folder only
      dockerfile: ./voicewake/docker/service-django-runserver.dockerfile
    volumes:
      #type+source+target for dev for real-time changes, without destroying+recreating container?
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
      - type: bind
        source: ./django_runserver.py
        target: /django_runserver.py
      - type: bind
        source: ./manage.py
        target: /manage.py
      - type: bind
        source: ./package.json
        target: /package.json
      - type: bind
        source: ./package-lock.json
        target: /package-lock.json
      - type: bind
        source: ./requirements.txt
        target: /requirements.txt
    # restart: always
    env_file:
      - /env/.env
    ports:
      #map port on host to port on container
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
  django_gunicorn:
    build:
      #context path dictates what "." points to in Dockerfile
      context: . #. because it relies on files like manage.py
      #dockerfile is relative to context path, and "../" can be used to reach context path's parent folder
      #seems like specifying until Dockerfile itself is needed, else "is a directory" error if folder only
      dockerfile: ./voicewake/docker/service-gunicorn.dockerfile
    volumes:
      #type+source+target for dev for real-time changes, without destroying+recreating container?
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
    # restart: always
    env_file:
      - /env/.env
    ports:
      #map port on host to port on container
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
  django_celery_worker:
    build:
      context: . #. because it relies on files like manage.py
      dockerfile: ./voicewake/docker/service-celery-worker.dockerfile
    volumes:
      #type+source+target for dev for real-time changes, without destroying+recreating container?
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
    # restart: always
    env_file:
      - /env/.env
    ports:
      #based on django_runserver/django_gunicorn
      - "8001:8001"
    depends_on:
      django_runserver:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend
  django_celery_beat:
    build:
      context: . #. because it relies on files like manage.py
      dockerfile: ./voicewake/docker/service-celery-beat.dockerfile
    volumes:
      #type+source+target for dev for real-time changes, without destroying+recreating container?
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
    # restart: always
    env_file:
      - /env/.env
    ports:
      #based on django_runserver/django_gunicorn
      - "8002:8002"
    depends_on:
      django_runserver:
        condition: service_healthy
      django_celery_worker:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "0.0.0.0:80:80"
    networks:
      - backend
  frontend:
    build:
      context: .  #. because it relies on ./static
      dockerfile: ./frontend/Dockerfile
    volumes:
      - /frontend/app_modules #supposedly for faster reload, but idk
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./frontend
        target: /frontend
    # command: npm run serve #dev
    ports:
      - "8080:8080"
    environment: 
      - CHOKIDAR_USEPOLLING=true #enables the hot reloading
  tailwind:
    #use tty to provide pseudo-terminal, since we have -i flag, i.e. input
    #we essentially can see when watcher finishes applying new changes
    tty: true
    build:
      context: .
    ports:
      - "3000:3000"
    #we use bind mount between host files and container files for two-way sync
    volumes:
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
      - type: bind
        source: ./frontend
        target: /frontend
      - type: bind
        source: ./tailwind.config.js
        target: /tailwind.config.js
volumes:
  static:
    #leave empty to use the container engine's default configuration for creating a volume
networks:
  backend:














# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

