#in compose.yaml, things such as "command" and "entrypoint" will override things like CMD and ENTRYPOINT at .dockerfile
  #therefore, it's best to resort to .dockerfile and entrypoint.sh before placing such things here
#.dockerignore is expected to be at root directory of build context, i.e. where you are running "docker build" from
name: vw_prod
services:
  django_gunicorn:
    build:
      #. because it relies on files like manage.py
      context: .
      dockerfile: ./voicewake/docker/service-gunicorn.dockerfile
    volumes:
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
    # restart: always
    env_file:
      - /env/prod.env
    ports:
      #map port on host to port on container
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://127.0.0.1:5000 || exit 1
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - backend

  django_celery_worker:
    build:
      #. because it relies on files like manage.py
      context: .
      dockerfile: ./voicewake/docker/service-celery-worker.dockerfile
    volumes:
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
    # restart: always
    env_file:
      - /env/prod.env
    ports:
      #based on django_runserver/django_gunicorn
      - "8001:8001"
    depends_on:
      django_gunicorn:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: celery -A voicewake status || exit 1
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - backend

  django_celery_beat:
    build:
      #. because it relies on files like manage.py
      context: .
      dockerfile: ./voicewake/docker/service-celery-beat.dockerfile
    volumes:
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
    # restart: always
    env_file:
      - /env/prod.env
    ports:
      #based on django_runserver/django_gunicorn
      - "8002:8002"
    depends_on:
      django_gunicorn:
        condition: service_healthy
      django_celery_worker:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: python manage.py shell -c "from voicewake.services import do_celery_beat_healthcheck; do_celery_beat_healthcheck();"
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 80s
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    environment:
      #base these off of actual Docker Django service name and its port
      - DJANGO_SERVICE_NAME=django_gunicorn
      - DJANGO_PORT=5000
      #favicon
      - FAVICON_URL=https://d3fpcqa3tewpp.cloudfront.net/static/prod/voicewake/favicon.svg
    ports:
      - "8080:8080"
    volumes:
      #Gunicorn will not serve /static/, so NGINX must do it directly
      - type: bind
        source: ./static
        target: /static
    depends_on:
      django_gunicorn:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      #NGINX will also fail if any upstream isn't responding, i.e. Django
      #force exit 1 if nginx status fails
      test: service nginx status || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

volumes:
  static:
    #leave empty to use the container engine's default configuration for creating a volume
networks:
  backend:
    #leave empty to use default driver



