#in compose.yaml, things such as "command" and "entrypoint" will override things like CMD and ENTRYPOINT at .dockerfile
  #therefore, it's best to resort to .dockerfile and entrypoint.sh before placing such things here
#.dockerignore is expected to be at root directory of build context, i.e. where you are running "docker build" from
services:
  test_service:
    env_file:
      - ./env/.env
    build:
      context: .  #. because it relies on ./static
      dockerfile: ./test_service.dockerfile

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    #env_file is only used and seen by the container being run, not during docker compose
    #to use .env file and fill it in here during docker compose: "docker-compose --env-file ./env/.env up -d"
      #--env-file must come before "up", else "unknown flag" error
    env_file:
      - ./env/.env
    environment:
      #these are presumably only for setup
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    #healthcheck seems to be required if you want other services to check it for "service_healthy" condition, else "dependency failed" error
    healthcheck:
      #must test with POSTGRES_DB and POSTGRES_USER, else it will try to use "root" and get "role 'root' does not exist"
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - backend

  redis:
    working_dir: /redis
    image: redis:latest
    #if always restart, then when a service has error/ends, it will restart again
    # restart: always
    ports:
      - "6379:6379"
    # volumes:
      # - /path/to/local/dаta:/root/redis
      # - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=somepassword
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    #even when loading, Redis can still return exit code 0, so to be sure it's ready, expect "PONG"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - backend

  django_runserver:
    build:
      context: .
      dockerfile: ./voicewake/docker/service-django-runserver.dockerfile
    volumes:
      #type+source+target for dev for real-time changes, without destroying+recreating container?
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
      - type: bind
        source: ./django_runserver.py
        target: /django_runserver.py
      - type: bind
        source: ./manage.py
        target: /manage.py
      - type: bind
        source: ./package.json
        target: /package.json
      - type: bind
        source: ./package-lock.json
        target: /package-lock.json
      - type: bind
        source: ./requirements.txt
        target: /requirements.txt
    # restart: always
    env_file:
      - /env/.env
    ports:
      #map port on host to port on container
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
    #no need healthcheck for runserver if we have docker_runserver.py

  django_gunicorn:
    build:
      #context path dictates what "." points to in Dockerfile
      context: . #. because it relies on files like manage.py
      #dockerfile is relative to context path, and "../" can be used to reach context path's parent folder
      #seems like specifying until Dockerfile itself is needed, else "is a directory" error if folder only
      dockerfile: ./voicewake/docker/service-gunicorn.dockerfile
    volumes:
      #type+source+target for dev for real-time changes, without destroying+recreating container?
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
    # restart: always
    env_file:
      - /env/.env
    ports:
      #map port on host to port on container
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://127.0.0.1:5000 || exit 1
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - backend

  django_celery_worker:
    build:
      context: . #. because it relies on files like manage.py
      dockerfile: ./voicewake/docker/service-celery-worker.dockerfile
    volumes:
      #type+source+target for dev for real-time changes, without destroying+recreating container?
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
    # restart: always
    env_file:
      - /env/.env
    ports:
      #based on django_runserver/django_gunicorn
      - "8001:8001"
    depends_on:
      django_gunicorn:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: celery -A voicewake status || exit 1
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - backend

  django_celery_beat:
    build:
      context: . #. because it relies on files like manage.py
      dockerfile: ./voicewake/docker/service-celery-beat.dockerfile
    volumes:
      #type+source+target for dev for real-time changes, without destroying+recreating container?
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
    # restart: always
    env_file:
      - /env/.env
    ports:
      #based on django_runserver/django_gunicorn
      - "8002:8002"
    depends_on:
      django_gunicorn:
        condition: service_healthy
      django_celery_worker:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: python manage.py shell -c "from voicewake.services import do_celery_beat_healthcheck; do_celery_beat_healthcheck();"
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 80s
    networks:
      - backend

  nginx:
    build: ./nginx
    environment:
      #base these off of actual Docker Django service name and its port
      - DJANGO_SERVICE_NAME=django_runserver
      - DJANGO_PORT=8000
    ports:
      - "8080:8080"
    depends_on:
      django_gunicorn:
        condition: service_healthy
    healthcheck:
      #NGINX will also fail if any upstream isn't responding, i.e. Django
      #force exit 1 if nginx status fails
      test: service nginx status || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  frontend:
    env_file:
      - ./env/.env
    build:
      context: .  #. because it relies on ./static
      dockerfile: ./frontend/Dockerfile
      #pass args for .dockerfile to use via ${ENV_NAME}
      args:
        VITE_PORT: ${VITE_PORT}
    volumes:
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./frontend
        target: /frontend
      #in container, specify the folder we want to ignore from bind-mount
      - /frontend/node_modules
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    environment: 
      #allows for hot reload for JS dev, e.g. Vue/React/etc.
      #hot reload will not work without it
      - CHOKIDAR_USEPOLLING=true

  tailwind:
    #must use tty
      #provide pseudo-terminal, since we have -i flag, i.e. input
      #can see when watcher finishes applying new changes
      #keeps container alive
    tty: true
    build:
      context: .
      dockerfile: ./service-tailwind.dockerfile
    ports:
      - "3000:3000"
    #we use bind mount between host files and container files for two-way sync
    volumes:
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./voicewake
        target: /voicewake
      - type: bind
        source: ./frontend
        target: /frontend
      - type: bind
        source: ./tailwind.config.js
        target: /tailwind.config.js
      #in container, specify the folder we want to ignore from bind-mount
      - /frontend/node_modules
volumes:
  static:
    #leave empty to use the container engine's default configuration for creating a volume
networks:
  backend:
    #leave empty to use default driver



