# Generated by Django 4.2.4 on 2023-08-24 20:57

from django.db import migrations
import os
import json
from django.conf import settings

#this isn't found at our models.py
from django.contrib.auth.models import Group



#expect args (apps, schema_editor) from migrations.RunPython
def fill_necessary_data(apps, schema_editor):

    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    app_name = "voicewake"

    EventTones = apps.get_model(app_name, "EventTones")
    GenericStatuses = apps.get_model(app_name, "GenericStatuses")
    EventRoles = apps.get_model(app_name, "EventRoles")

    #Group
    Group.objects.create(name="regular")

    #EventTones
    with open(os.path.join(settings.BASE_DIR, 'voicewake/static/json/data_emojis_final.json'), encoding="utf8") as file:

        emojis = json.load(file)
        emojis = emojis.items()

        #store for bulk_create
        new_rows = []

        for row in emojis:

            (key, symbol) = row

            new_rows.append(
                EventTones(
                    event_tone_slug=key.replace("_", "-"),
                    event_tone_name=key.replace("_"," "),
                    event_tone_symbol=symbol,
                )
            )

        #bulk_create
        EventTones.objects.bulk_create(
            new_rows,
            ignore_conflicts=True
        )

        file.close()

    #GenericStatuses
    GenericStatuses.objects.bulk_create(
        [
            GenericStatuses(generic_status_name='ok'),
            GenericStatuses(generic_status_name='deleted'),
            GenericStatuses(generic_status_name='incomplete'),
            GenericStatuses(generic_status_name='completed'),
        ],
        ignore_conflicts=True
    )

    EventRoles.objects.bulk_create(
        [
            EventRoles(event_role_name='originator'),
            EventRoles(event_role_name='responder')
        ],
        ignore_conflicts=True
    )

    print("\nFinished populating db with necessary data.")


custom_function_get_id_of_one_or_all_event_tones_via_slug = '''
    CREATE OR REPLACE FUNCTION get_id_of_one_or_all_event_tones_via_slug(slug VARCHAR)
        RETURNS TABLE (
            id BIGINT
        ) AS
        $$
        BEGIN
            IF EXISTS(SELECT * FROM event_tones WHERE event_tones.event_tone_slug = slug) THEN
                RETURN QUERY(SELECT event_tones.id FROM event_tones WHERE event_tones.event_tone_slug = slug);
            ELSE
                RETURN QUERY(SELECT event_tones.id FROM event_tones);
            END IF;
        END;
        $$
        LANGUAGE plpgsql;
'''

#the "OLD.is_liked IS FALSE AND NEW.is_liked IS TRUE" and vice versa part is important
#to protect against race condition redundancy, i.e. multiple requests with same action
custom_function_handle_event_likes_dislikes_count = '''
    CREATE OR REPLACE FUNCTION handle_event_likes_dislikes_count() RETURNS TRIGGER AS $$
        BEGIN
            IF (TG_OP = 'INSERT') THEN
                IF (NEW.is_liked IS TRUE) THEN
                    UPDATE events
                    SET like_count = like_count + 1
                    WHERE id = NEW.event_id
                    ;
                ELSIF (NEW.is_liked IS FALSE) THEN
                    UPDATE events
                    SET dislike_count = dislike_count + 1
                    WHERE id = NEW.event_id
                    ;
                END IF;
                RETURN NEW;
            ELSIF (TG_OP = 'UPDATE') THEN
                IF (OLD.is_liked IS FALSE AND NEW.is_liked IS TRUE) THEN
                    UPDATE events
                    SET like_count = like_count + 1,
                    dislike_count = dislike_count - 1
                    WHERE id = NEW.event_id
                    ;
                ELSIF (OLD.is_liked IS TRUE AND NEW.is_liked IS FALSE) THEN
                    UPDATE events
                    SET like_count = like_count - 1,
                    dislike_count = dislike_count + 1
                    WHERE id = NEW.event_id
                    ;
                END IF;
                RETURN NEW;
            ELSIF (TG_OP = 'DELETE') THEN
                IF (OLD.is_liked IS TRUE) THEN
                    UPDATE events
                    SET like_count = like_count - 1
                    WHERE id = OLD.event_id
                    ;
                ELSIF (OLD.is_liked IS FALSE) THEN
                    UPDATE events
                    SET dislike_count = dislike_count - 1
                    WHERE id = OLD.event_id
                    ;
                END IF;
                RETURN OLD;
            END IF;
            RETURN NULL;
        END;
    $$ LANGUAGE plpgsql VOLATILE;
'''

custom_trigger_event_likes_dislikes = '''
    CREATE TRIGGER trigger_event_likes_dislikes
    AFTER INSERT
    OR UPDATE OF is_liked 
    OR DELETE
    ON event_likes_dislikes
    FOR EACH ROW
    EXECUTE FUNCTION handle_event_likes_dislikes_count();
'''



class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(custom_function_get_id_of_one_or_all_event_tones_via_slug),
        migrations.RunSQL(custom_function_handle_event_likes_dislikes_count),
        migrations.RunSQL(custom_trigger_event_likes_dislikes),
        migrations.RunPython(fill_necessary_data),
    ]