"""
Django settings for voicewake project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

#Python packages
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hdgs8@4nxkx0du^2n-gdss(!eo6i0kj6vk=gx1mddc@g=6h_^1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',     #requires SITE_ID later, so db can manage content for multiple sites

    'rest_framework',
    #optional, provides template when returning Response() and not JsonResponse()
    #Django expects this when returning Response(), else error TemplateDoesNotExist ... rest_framework/api.html

    #app from apps.py
    'voicewake.apps.VoicewakeConfig',

    #token for DRF
    'rest_framework.authtoken',

    #channels for websocket
    # 'channels',

    #fontawesome, installed via requirements.txt
    'fontawesomefree',

    #debug
    'debug_toolbar',

    #OTP
    'django_otp',
    # 'django_otp.plugins.otp_totp',
    # 'django_otp.plugins.otp_hotp',
    # 'django_otp.plugins.otp_static',

    #allauth
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',

    #social providers
    # 'allauth.socialaccount.providers.google',
]


#if this doesn't work, check django_site in db
SITE_ID = 1


#custom user model
AUTH_USER_MODEL = 'voicewake.User'

#if you have issues with bootstrap, try this:
# CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
# CRISPY_TEMPLATE_PACK = 'bootstrap5'

MIDDLEWARE = []

#development
if DEBUG is True:

    REQUEST_TIME_DELAY = 1  #seconds

    MIDDLEWARE += [
        'voicewake.middleware.drf_api_delay_middleware.TimeDelayMiddleware'
    ]

#standard
MIDDLEWARE += [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #own middleware
    # 'voicewake.middleware.set_user_timezone_middleware.SetUserTimezoneMiddleware',
]

ROOT_URLCONF = 'voicewake.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'voicewake/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'voicewake.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {  
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'voicewake',
        'USER': 'postgres',
        'PASSWORD': 'postgresqllocalhost',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


#not needed, but required by django-debug-toolbar
if DEBUG is True:

    INTERNAL_IPS = [
        '127.0.0.1',
    ]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_URL = 'static/'  #my_app/static

#extra static directories
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),   #this is where Django can find our Vue content
]

STATIC_ROOT = 'deploy/static_root'  #collect all static files for live server


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#using '/' instead of new URL for '/home'
#'/' does not need to be specified at urlpatterns
#'' did not work

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


#timezone management
#TIME_ZONE default is 'America/Chicago', which was the case here, causing templates to have UTC -5
#when USE_TZ=False, Django stores datetime as UTC, and you should remove TIME_ZONE
#when USE_TZ=True: create data at 23:00 MY (UTC +8) --> stores as 23:00+08 --> template shows 15:00
USE_TZ = True
TIME_ZONE = 'UTC'

#DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
        'rest_framework.permissions.IsAdminUser',
    ],
}


ASGI_APPLICATION = 'voicewake.asgi.application'


#on deploy, use Redis, not the current one below
CHANNEL_LAYERS = {
    'default': {
                'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


#folder name, only for storage
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
#URL, trailing slash is compulsory, must not include domain URL
MEDIA_URL = '/media/'


#if you want to hide Django Debug Toolbar, put False
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda r: False,
}


#MEDIA SIZES
#in bytes, so when x/(1024*1024), is 3mb
FILE_UPLOAD_MAX_MEMORY_SIZE = 3072000   #threshold for processing files in memory instead, i.e. much faster
EVENT_MAX_FILE_SIZE_BYTES = 3072000


#EVENT
EVENT_ROOM_CREATE_DAILY_LIMIT = 10      #compares from 00:00:00 UTC
EVENT_ROOM_REPLY_DAILY_LIMIT = 10       #compares from 00:00:00 UTC
EVENT_CHOICE_EXPIRY_SECONDS = 1200      #20 mins, when locked but is_replying=False
EVENT_REPLY_EXPIRY_SECONDS = 3600       #60 mins, when locked and is_replying=True


#EMAIL
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
MAILER_EMAIL_BACKEND = EMAIL_BACKEND
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'adrianchangcy@gmail.com'
EMAIL_HOST_PASSWORD = 'qjxtrlcllrtbnmvn'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


#TOTP token arguments
#key minimum 120 bits, recommended 160 bits
#1 byte is 8 bits, so therefore minimum 15 bytes, recommended 20 bytes
TOTP_KEY_BYTE_SIZE = 20         #to pass into secrets.token_bytes(int) for creating totp_key
TOTP_NUMBER_OF_DIGITS = 6       #digits in OTP
TOTP_VALIDITY_SECONDS = 300     #seconds until expiry, a.k.a. steps
TOTP_TOLERANCE_SECONDS = 120    #allow early/late by x seconds until truly not allowed


#UserOTP-related arguments
OTP_CREATE_TIMEOUT_SECONDS = 30    #for creating new OTP
OTP_MAX_ATTEMPTS = 6            #times someone can try before being timed out
OTP_MAX_ATTEMPT_TIMEOUT_SECONDS = 600



