<template>
    <TransitionGroup
        name="transition-group-fade"
        enter-from-class="opacity-0"
        enter-active-class="transition-opacity"
        enter-to-class="opacity-100"
        leave-from-class="opacity-100"
        leave-active-class="transition-opacity"
        leave-to-class="opacity-0"
    >
        <slot></slot>
    </TransitionGroup>
</template>