# Generated by Django 4.2.4 on 2023-10-23 10:11

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import voicewake.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_lowercase', models.CharField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, default=None, max_length=30, null=True, unique=True)),
                ('username_lowercase', models.CharField(blank=True, default=None, max_length=30, null=True, unique=True)),
                ('totp_key', models.BinaryField()),
                ('password', models.CharField(max_length=128)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('banned_until', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioClipRequestStatuses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('audio_clip_request_status_name', models.TextField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audio_clip_request_statuses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AudioClipRoles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('audio_clip_role_name', models.TextField(max_length=20, unique=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audio_clip_roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AudioClipTones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('audio_clip_tone_slug', models.TextField(default=None, max_length=50, unique=True)),
                ('audio_clip_tone_name', models.TextField(default=None, max_length=50, unique=True)),
                ('audio_clip_tone_symbol', models.TextField(default=None, max_length=50, unique=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audio_clip_tones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_name', models.TextField(default='-', max_length=200)),
                ('when_locked', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_replying', models.BooleanField(blank=True, default=None, null=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_user_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GenericStatuses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('generic_status_name', models.TextField(max_length=200, unique=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'generic_statuses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_permission_name', models.TextField()),
                ('when_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_permissions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserVerificationOptions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_verification_option_name', models.TextField(max_length=20, unique=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_verification_options',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserVerificationStatuses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_verification_status_name', models.TextField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_verification_statuses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('otp_last_created', models.DateTimeField(blank=True, default=None, null=True)),
                ('otp_attempts', models.SmallIntegerField(default=0)),
                ('otp_last_attempted', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_otp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserFavourites',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('favourited_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites_user_2', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites_user_1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_favourites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserEvents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('when_seen_at_front_page', models.DateTimeField(blank=True, default=None, null=True)),
                ('when_excluded_for_reply', models.DateTimeField(blank=True, default=None, null=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='voicewake.events')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserBlocks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blocks_user_2', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blocks_user_1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_blocks',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='events',
            name='generic_status',
            field=models.ForeignKey(default=voicewake.models.get_default_generic_status, on_delete=django.db.models.deletion.PROTECT, to='voicewake.genericstatuses'),
        ),
        migrations.AddField(
            model_name='events',
            name='locked_for_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_user_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AudioClipToneTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('translation', models.TextField()),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('audio_clip_tone', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='voicewake.audiocliptones')),
            ],
            options={
                'db_table': 'audio_clip_tone_translations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AudioClips',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=voicewake.models.determine_audio_clip_audio_file_path_and_name)),
                ('audio_duration_s', models.IntegerField(default=0)),
                ('audio_volume_peaks', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, default=0, max_digits=3), default=None, null=True, size=20)),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('audio_clip_role', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='voicewake.audiocliproles')),
                ('audio_clip_tone', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voicewake.audiocliptones')),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='voicewake.events')),
                ('generic_status', models.ForeignKey(default=voicewake.models.get_default_generic_status, on_delete=django.db.models.deletion.PROTECT, to='voicewake.genericstatuses')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audio_clips',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AudioClipRequests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('audio_clip_request_status', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='voicewake.audiocliprequeststatuses')),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='voicewake.events')),
                ('requested_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_clip_requests_user_2', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_clip_requests_user_1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audio_clip_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AudioClipReports',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('reported_audio_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicewake.audioclips')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audio_clip_reports',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AudioClipLikesDislikes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_liked', models.BooleanField()),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('audio_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicewake.audioclips')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audio_clip_likes_dislikes',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='userevents',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event'),
        ),
        migrations.AddConstraint(
            model_name='userblocks',
            constraint=models.UniqueConstraint(fields=('user', 'blocked_user'), name='unique_user_blocked_user'),
        ),
        migrations.AddConstraint(
            model_name='audioclipreports',
            constraint=models.UniqueConstraint(fields=('user', 'reported_audio_clip'), name='unique_user_reported_audio_clip'),
        ),
        migrations.AddConstraint(
            model_name='audiocliplikesdislikes',
            constraint=models.UniqueConstraint(fields=('user', 'audio_clip'), name='unique_audio_clip_likes_dislikes_1'),
        ),
    ]
