# Generated by Django 4.2.7 on 2024-02-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', 'migration_essentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiocliprequeststatuses',
            name='audio_clip_request_status_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='audiocliproles',
            name='audio_clip_role_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='audioclips',
            name='audio_file',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='audiocliptones',
            name='audio_clip_tone_name',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='audiocliptones',
            name='audio_clip_tone_slug',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='audiocliptones',
            name='audio_clip_tone_symbol',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='genericstatuses',
            name='generic_status_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='user_permission_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='userverificationoptions',
            name='user_verification_option_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userverificationstatuses',
            name='user_verification_status_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
