# Generated by Django 4.1.5 on 2023-06-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totp_key',
            field=models.BinaryField(),
        ),
    ]
