# Generated by Django 4.2.7 on 2023-11-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0001_eventreplyqueues_last_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioclips',
            name='is_banned',
        ),
        migrations.AddField(
            model_name='audioclips',
            name='when_banned',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
