# Generated by Django 4.2.4 on 2023-10-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0001_remove_userotp_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userotp',
            old_name='attempts',
            new_name='otp_attempts',
        ),
        migrations.RenameField(
            model_name='userotp',
            old_name='last_attempted',
            new_name='otp_last_attempted',
        ),
        migrations.RenameField(
            model_name='userotp',
            old_name='when_created',
            new_name='otp_last_created',
        ),
        migrations.AddField(
            model_name='userotp',
            name='otp_created_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
