# Generated by Django 4.1.5 on 2023-06-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
