# Generated by Django 4.0.4 on 2022-08-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='language',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='is_legitimate',
        ),
    ]
