# Generated by Django 4.1.5 on 2023-04-03 16:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='audio_volume_peaks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), default=list, size=10),
        ),
    ]
