# Generated by Django 4.1.5 on 2023-05-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usereventrooms',
            old_name='is_reply_skipped',
            new_name='is_excluded_for_reply',
        ),
        migrations.RenameField(
            model_name='usereventrooms',
            old_name='is_browsed',
            new_name='is_seen_at_front_page',
        ),
    ]
