# Generated by Django 4.2.4 on 2023-09-22 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0001_migration_essentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReportBans',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('banned_until', models.DateTimeField()),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('reported_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='voicewake.events')),
            ],
            options={
                'db_table': 'event_report_bans',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventReports',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('reported_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicewake.events')),
            ],
            options={
                'db_table': 'event_reports',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
        migrations.AddField(
            model_name='user',
            name='banned_until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='UserEventReports',
        ),
        migrations.AddField(
            model_name='eventreports',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='eventreports',
            constraint=models.UniqueConstraint(fields=('user', 'reported_event'), name='unique_user_reported_event'),
        ),
    ]
