# Generated by Django 4.0.4 on 2022-07-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRepeatDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_repeat', models.BooleanField()),
                ('trigger_mon_to_sun', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_repeat_details',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EventSchedules',
        ),
    ]
