# Generated by Django 4.1.5 on 2023-05-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0002_rename_is_reply_skipped_usereventrooms_is_excluded_for_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereventrooms',
            name='is_excluded_for_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usereventrooms',
            name='is_seen_at_front_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='usereventrooms',
            unique_together={('user', 'event_room')},
        ),
    ]
