# Generated by Django 4.1.5 on 2023-04-03 17:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0002_events_audio_volume_peaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='audio_volume_peaks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, default=0, max_digits=3), default=list, size=10),
        ),
    ]
