# Generated by Django 4.0.4 on 2022-08-26 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0002_remove_events_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='language',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voicewake.languages'),
        ),
    ]
