# Generated by Django 4.2.4 on 2023-10-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0002_rename_attempts_userotp_otp_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='otp_created_count',
        ),
    ]
