# Generated by Django 4.0.4 on 2022-07-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0002_eventrepeatdetails_delete_eventschedules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventGroups',
        ),
    ]
