# Generated by Django 4.2.7 on 2023-11-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0002_remove_audioclips_is_banned_audioclips_when_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioclips',
            name='when_banned',
        ),
        migrations.AddField(
            model_name='audioclips',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
