# Generated by Django 4.1.5 on 2023-07-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0002_delete_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtones',
            name='event_tone_slug',
            field=models.TextField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtones',
            name='event_tone_name',
            field=models.TextField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtones',
            name='event_tone_symbol',
            field=models.TextField(default=None, max_length=50, unique=True),
        ),
    ]
