# Generated by Django 4.2.4 on 2023-08-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0002_alter_events_audio_duration_s'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usereventrooms',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='usereventrooms',
            constraint=models.UniqueConstraint(fields=('user', 'event_room'), name='unique_user_event_room'),
        ),
    ]
