# Generated by Django 4.0.4 on 2022-07-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0003_delete_eventgroups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventInstances',
        ),
    ]
