# Generated by Django 4.2.7 on 2023-11-20 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0003_remove_audioclips_when_banned_audioclips_is_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioClipBans',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('last_evaluated', models.DateTimeField(blank=True, default=None, null=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audio_clip_bans',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='audioclips',
            name='is_banned',
        ),
        migrations.DeleteModel(
            name='AudioClipReports',
        ),
        migrations.AddField(
            model_name='audioclipbans',
            name='audio_clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicewake.audioclips'),
        ),
    ]
