# Generated by Django 4.2.4 on 2023-10-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0003_remove_userotp_otp_created_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_last_attempted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp_last_created',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
