# Generated by Django 4.1.5 on 2023-04-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0003_alter_events_audio_volume_peaks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_status',
        ),
        migrations.DeleteModel(
            name='EventStatuses',
        ),
    ]
