# Generated by Django 4.0.4 on 2022-08-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0003_events_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='when_locked',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
