# Generated by Django 4.1.5 on 2023-07-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0003_eventtones_event_tone_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='audio_file_seconds',
        ),
    ]
