# Generated by Django 4.0.4 on 2022-08-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0004_delete_eventinstances'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventpurposes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventpurposetranslations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventrepeatdetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventrequests',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventrequeststatuses',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventroles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventroommatches',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventroommatchreportchoices',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventroommatchreports',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventrooms',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventstatuses',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventtones',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventtonetranslations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userdetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usereventroles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userfavourites',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userpermissions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userverificationoptions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userverificationstatuses',
            options={'managed': True},
        ),
    ]
