# Generated by Django 4.2.7 on 2023-11-20 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0004_audioclipbans_remove_audioclips_is_banned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioClipReports',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_evaluated', models.DateTimeField(blank=True, default=None, null=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audio_clip_reports',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='audioclips',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AudioClipBans',
        ),
        migrations.AddField(
            model_name='audioclipreports',
            name='audio_clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicewake.audioclips'),
        ),
    ]
