# Generated by Django 4.1.5 on 2023-04-04 17:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0004_remove_events_event_status_delete_eventstatuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='audio_volume_peaks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, default=0, max_digits=3), default=list, size=20),
        ),
    ]
