# Generated by Django 4.0.4 on 2022-08-29 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0004_events_when_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country_name',
            field=models.TextField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_name_shortened',
            field=models.TextField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eventpurposes',
            name='event_purpose_name',
            field=models.TextField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='eventrequeststatuses',
            name='event_request_status_name',
            field=models.TextField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='eventroles',
            name='event_role_name',
            field=models.TextField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='eventroommatchreportchoices',
            name='event_room_match_report_choice_name',
            field=models.TextField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='eventstatuses',
            name='event_status_name',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtones',
            name='event_tone_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='languages',
            name='language_name',
            field=models.TextField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='language_name_shortened',
            field=models.TextField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='voicewake.authuser'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_display_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userverificationoptions',
            name='user_verification_option_name',
            field=models.TextField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userverificationstatuses',
            name='user_verification_status_name',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
