# Generated by Django 4.0.4 on 2022-08-29 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0005_alter_countries_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='voicewake.authuser', unique=True),
        ),
    ]
