# Generated by Django 4.2.7 on 2023-11-20 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0005_audioclipreports_audioclips_is_banned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioclipreports',
            name='last_reported',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
