# Generated by Django 4.1.5 on 2023-04-07 03:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import voicewake.models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0005_alter_events_audio_volume_peaks'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericStatuses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('generic_status_name', models.TextField(max_length=200)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'generic_statuses',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='events',
            name='audio_volume_peaks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, default=0, max_digits=3), default=None, null=True, size=20),
        ),
        migrations.AddField(
            model_name='eventrooms',
            name='generic_status',
            field=models.ForeignKey(default=voicewake.models.get_default_generic_status, on_delete=django.db.models.deletion.PROTECT, to='voicewake.genericstatuses'),
        ),
        migrations.AddField(
            model_name='events',
            name='generic_status',
            field=models.ForeignKey(default=voicewake.models.get_default_generic_status, on_delete=django.db.models.deletion.PROTECT, to='voicewake.genericstatuses'),
        ),
    ]
