# Generated by Django 4.2.7 on 2023-11-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0006_audioclipreports_last_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioclipreports',
            name='last_reported',
        ),
    ]
