# Generated by Django 4.1.5 on 2023-04-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0006_genericstatuses_alter_events_audio_volume_peaks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='audio_file_seconds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
