# Generated by Django 4.0.4 on 2022-08-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0007_alter_userdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventroommatches',
            name='when_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.TextField(max_length=40),
        ),
    ]
