# Generated by Django 4.1.5 on 2023-04-28 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0007_events_audio_file_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrooms',
            name='locked_for_user',
        ),
        migrations.RemoveField(
            model_name='eventrooms',
            name='when_locked',
        ),
        migrations.CreateModel(
            name='EventRoomLocks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_replying', models.BooleanField(default=False)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('event_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicewake.eventrooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicewake.authuser')),
            ],
            options={
                'db_table': 'event_room_locks',
                'managed': True,
            },
        ),
    ]
