# Generated by Django 4.0.4 on 2022-09-04 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0008_alter_eventroommatches_when_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventroommatches',
            name='ending_message',
        ),
        migrations.RemoveField(
            model_name='eventroommatches',
            name='ending_score',
        ),
        migrations.AddField(
            model_name='eventrooms',
            name='event_room_name',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='eventroommatchreports',
            name='event_room_match',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_room_match_reports1', to='voicewake.eventroommatches'),
        ),
        migrations.AlterField(
            model_name='eventroommatchreports',
            name='reported_event_room_match',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_room_match_reports2', to='voicewake.eventroommatches'),
        ),
        migrations.CreateModel(
            name='EventRoomMatchRatings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ending_score', models.IntegerField(blank=True, default=3, null=True)),
                ('ending_message', models.TextField(blank=True, null=True)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('event_room_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_room_match_ratings1', to='voicewake.eventroommatches')),
                ('rated_event_room_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_room_match_ratings2', to='voicewake.eventroommatches')),
            ],
            options={
                'db_table': 'event_room_match_ratings',
                'managed': True,
            },
        ),
    ]
