# Generated by Django 4.1.5 on 2023-04-28 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0008_remove_eventrooms_locked_for_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventroomlocks',
            name='event_room',
        ),
        migrations.AddField(
            model_name='eventrooms',
            name='event_room_lock',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voicewake.eventroomlocks'),
        ),
    ]
