# Generated by Django 4.2.7 on 2023-11-30 14:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0008_audioclipreports_last_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioclips',
            name='like_dislike_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=3),
        ),
    ]
