# Generated by Django 4.1.5 on 2023-04-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0009_remove_eventroomlocks_event_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericstatuses',
            name='generic_status_name',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
