# Generated by Django 4.2.7 on 2023-12-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0009_audioclips_like_dislike_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioclips',
            old_name='like_dislike_ratio',
            new_name='like_ratio',
        ),
    ]
