# Generated by Django 4.0.4 on 2022-09-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0009_remove_eventroommatches_ending_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventroommatchratings',
            name='ending_message',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
