# Generated by Django 4.1.5 on 2023-04-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0010_alter_genericstatuses_generic_status_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrooms',
            name='event_room_lock',
        ),
        migrations.AddField(
            model_name='eventrooms',
            name='is_replying',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='eventrooms',
            name='locked_for_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voicewake.authuser'),
        ),
        migrations.AddField(
            model_name='eventrooms',
            name='when_locked',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='EventRoomLocks',
        ),
    ]
