# Generated by Django 4.0.4 on 2022-09-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0010_alter_eventroommatchratings_ending_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventroommatchratings',
            old_name='ending_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='eventroommatchratings',
            old_name='ending_score',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='usereventroles',
            old_name='given_scores',
            new_name='given_ratings',
        ),
    ]
