# Generated by Django 4.2.7 on 2023-12-01 14:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0010_rename_like_dislike_ratio_audioclips_like_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioclips',
            name='like_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3),
        ),
    ]
