# Generated by Django 4.2.7 on 2023-12-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0011_alter_audioclips_like_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
