# Generated by Django 4.0.4 on 2022-09-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0011_rename_ending_message_eventroommatchratings_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventroommatchratings',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
