# Generated by Django 4.2.7 on 2023-12-12 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0012_user_ban_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioclipreports',
            name='audio_clip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voicewake.audioclips'),
        ),
    ]
