# Generated by Django 4.1.5 on 2023-02-01 07:45

from django.db import migrations, models
import voicewake.models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0012_alter_eventroommatchratings_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventroommatchratings',
            name='rating',
            field=models.IntegerField(default=3, validators=[voicewake.models.validate_rating]),
        ),
    ]
