# Generated by Django 4.2.7 on 2023-12-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0013_alter_audioclipreports_audio_clip'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='audiocliplikesdislikes',
            index=models.Index(fields=['user_id', 'last_modified', 'id'], name='audio_clip__user_id_3e52f8_idx'),
        ),
        migrations.AddIndex(
            model_name='audioclipreports',
            index=models.Index(models.OrderBy(models.F('last_evaluated'), nulls_first=True), name='acr_last_evaluated_1'),
        ),
        migrations.AddIndex(
            model_name='audioclips',
            index=models.Index(fields=['when_created', 'id'], name='audio_clips_when_cr_c54694_idx'),
        ),
        migrations.AddIndex(
            model_name='audioclips',
            index=models.Index(fields=['last_modified', 'id'], name='audio_clips_last_mo_92c145_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreplyqueues',
            index=models.Index(fields=['when_locked'], name='event_reply_when_lo_494338_idx'),
        ),
        migrations.AddIndex(
            model_name='userblocks',
            index=models.Index(fields=['when_created', 'id'], name='user_blocks_when_cr_bc5853_idx'),
        ),
    ]
