# Generated by Django 4.1.5 on 2023-02-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0013_alter_eventroommatchratings_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtones',
            name='event_tone_symbol',
            field=models.TextField(default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventtones',
            name='event_tone_name',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
