# Generated by Django 4.1.5 on 2023-02-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0014_eventtones_event_tone_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtones',
            name='event_tone_symbol',
            field=models.TextField(max_length=50),
        ),
    ]
