# Generated by Django 4.1.5 on 2023-03-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0016_alter_eventtones_event_tone_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLikesDislikes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_liked', models.BooleanField()),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_likes_dislikes',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='eventpurposetranslations',
            name='event_purpose',
        ),
        migrations.RemoveField(
            model_name='eventpurposetranslations',
            name='language',
        ),
        migrations.RemoveField(
            model_name='eventrepeatdetails',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventrooms',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='eventrooms',
            name='event_room_name',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_message',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_purpose',
        ),
        migrations.RemoveField(
            model_name='events',
            name='language',
        ),
        migrations.RemoveField(
            model_name='events',
            name='when_trigger',
        ),
        migrations.RemoveField(
            model_name='usereventroles',
            name='given_ratings',
        ),
        migrations.AddField(
            model_name='events',
            name='event_room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voicewake.eventrooms'),
        ),
        migrations.DeleteModel(
            name='EventPurposes',
        ),
        migrations.DeleteModel(
            name='EventPurposeTranslations',
        ),
        migrations.DeleteModel(
            name='EventRepeatDetails',
        ),
        migrations.AddField(
            model_name='eventlikesdislikes',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voicewake.events'),
        ),
        migrations.AddField(
            model_name='eventlikesdislikes',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='voicewake.authuser'),
        ),
    ]
