# Generated by Django 4.1.5 on 2023-03-10 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicewake', '0017_eventlikesdislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventroommatchratings',
            name='event_room_match',
        ),
        migrations.RemoveField(
            model_name='eventroommatchratings',
            name='rated_event_room_match',
        ),
        migrations.RemoveField(
            model_name='eventroommatchreports',
            name='event_room_match',
        ),
        migrations.RemoveField(
            model_name='eventroommatchreports',
            name='event_room_match_report_choice',
        ),
        migrations.RemoveField(
            model_name='eventroommatchreports',
            name='reported_event_room_match',
        ),
        migrations.DeleteModel(
            name='EventRoomMatches',
        ),
        migrations.DeleteModel(
            name='EventRoomMatchRatings',
        ),
        migrations.DeleteModel(
            name='EventRoomMatchReportChoices',
        ),
        migrations.DeleteModel(
            name='EventRoomMatchReports',
        ),
    ]
