user  nginx;


worker_processes  1;
events {
    worker_connections  10000;
}
worker_rlimit_nofile  20000;


error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


#we put this here instead of http to make it easier
#just have to take extra precaution on not to match $var meant for NGINX with actual environment variables
include /etc/nginx/conf.d/*conf;
