#for things that went wrong, refer to: project > Actions > all workflows

#workflow:
  #done with feature branch, do pull request to main: test, collectstatic, build, deploy to stage
  #pull request successful (merged): test, collectstatic, build, deploy to prod

#notes:
  #commit to feature branch, then when making pull request, it takes the main.yaml at HEAD of the branch for Github Actions
    #on close and reopen pull request, it reuses that same main.yaml, without referring to newer main.yaml

name: test, collectstatic, build, deploy

on:
  pull_request:
    #currently using "opened" only to run tests and nothing else
    #"closed" is bad, as closed covers both merged and not merged
    #on merge, build and deploy to ECR, refer to this (not sure where to define in .yaml):
      #https://github.com/orgs/community/discussions/26724#discussioncomment-3253096
    types: [opened]

jobs:
  run_test:
    #specify environment to choose from git > settings > environments
    #https://stackoverflow.com/questions/66521958/how-to-access-environment-secrets-from-a-github-workflow
    environment: dev
    runs-on: ubuntu-latest
    container:
      image: python:latest
    #postgres, redis
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379    
    #run django tests
    #always using dev
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Install Django dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python manage.py test voicewake.tests.test_apis.Users_TestCase
        env:
          GIT_PR_NUMBER: ${{ github.event.pull_request.number }}
          DJANGO_SETTINGS_MODULE: voicewake.settings.dev
          SECRET_KEY: abc123
          ALLOWED_HOSTS: "*"
          DB_HOST: postgres
          DB_NAME: voicewake
          DB_USER: postgres
          DB_PASSWORD: localhost
          DB_PORT: 5432
          REDIS_ENDPOINT: redis://redis
          #tests don't use actual email, so leave AWS_SES empty
          AWS_SES_HOST:
          AWS_SES_SMTP_USER_NAME:
          AWS_SES_SMTP_PASSWORD:
          AWS_SES_FROM_EMAIL:
          AWS_SES_IAM_USER_NAME:
          #at github secrets
          AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_S3_REGION_NAME: ${{ secrets.AWS_S3_REGION_NAME }}
          AWS_S3_CUSTOM_DOMAIN: ${{ secrets.AWS_S3_CUSTOM_DOMAIN }}
          AWS_S3_STATIC_BUCKET_NAME: ${{ secrets.AWS_S3_STATIC_BUCKET_NAME }}
          AWS_S3_MEDIA_BUCKET_NAME: ${{ secrets.AWS_S3_MEDIA_BUCKET_NAME }}
          AWS_S3_UGC_UNPROCESSED_BUCKET_NAME: ${{ secrets.AWS_S3_UGC_UNPROCESSED_BUCKET_NAME }}
          AWS_LAMBDA_ACCESS_KEY_ID: ${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }}
          AWS_LAMBDA_SECRET_ACCESS_KEY: ${{ secrets.AWS_LAMBDA_SECRET_ACCESS_KEY }}
          AWS_LAMBDA_REGION_NAME: ${{ secrets.AWS_LAMBDA_REGION_NAME }}
          AWS_LAMBDA_NORMALISE_FUNCTION_NAME: ${{ secrets.AWS_LAMBDA_NORMALISE_FUNCTION_NAME }}
          AWS_ECR_REGION_NAME: ${{ secrets.AWS_ECR_REGION_NAME }}
          AWS_ECR_ACCOUNT_ID: ${{ secrets.AWS_ECR_ACCOUNT_ID }}
  # collectstatic:
  # build_frontend:
  # deploy_stage:
  #   if: github.event.pull_request.merged == false
  #   #...
  # deploy_prod:
  #   if: github.event.pull_request.merged == true
  #   #...

















