#for things that went wrong, refer to: project > Actions > all workflows

#consider this to test github actions locally:
  #https://github.com/nektos/act

#PREREQUISITE
#to avoid using long-lived secrets, there's a recommended whole headache to setting up OpenID Connect (OIDC)
  #at IAM > policies > add all ECR actions in it
  #at IAM > identity providers > add >
    #provider type: OpenID Connect
    #provider URL: https://token.actions.githubusercontent.com
    #audience: sts.amazonaws.com
  #at IAM > roles > create >
    #trusted identity type: Web identity
    #identity provider: the one you created, should be listed as "token.actions.githubusercontent.com"
    #audience: sts.amazonaws.com
    #github organization: your_github_username_or_actual_github_org
    #permission: select the ECR policy with all ECR actions
  #resources
    #https://docs.github.com/en/actions/how-tos/secure-your-work/security-harden-deployments

#testing notes:
  #to skip jobs:
    #do "if: false" inside a job
  #to only run a job on pull request merged:
    #github.event.pull_request.merged == true

name: Run tests, build and deploy to ECR, collectstatic to S3

on:
  pull_request:
    #currently using "opened" only to run tests and nothing else
    #"closed" alone is bad, as closed covers both merged and not merged, so also check for: github.event.pull_request.merged
    #on merge, build and deploy to ECR, refer to this (not sure where to define in .yaml):
      #https://github.com/orgs/community/discussions/26724#discussioncomment-3253096
    types: [opened, reopened, closed]

jobs:
  curiosity_on_pr_close:
    #specify environment to choose from git > settings > environments
    #https://stackoverflow.com/questions/66521958/how-to-access-environment-secrets-from-a-github-workflow
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: hmm
        run: |
          echo "${{ github.event.action == 'closed' }}"
          echo "${{ github.event.pull_request.merged == false }}"

