#for things that went wrong, refer to: project > Actions > all workflows

#consider this to test github actions locally:
  #https://github.com/nektos/act

#to avoid using long-lived secrets, there's a recommended whole headache to setting up OpenID Connect (OIDC)
  #at IAM > policies > add all ECR actions in it
  #at IAM > identity providers > add >
    #provider type: OpenID Connect
    #provider URL: https://token.actions.githubusercontent.com
    #audience: sts.amazonaws.com
  #at IAM > roles > create >
    #trusted identity type: Web identity
    #identity provider: the one you created, should be listed as "token.actions.githubusercontent.com"
    #audience: sts.amazonaws.com
    #github organization: your_github_username_or_actual_github_org
    #permission: select the ECR policy with all ECR actions

  #resources
    #***https://docs.github.com/en/actions/how-tos/secure-your-work/security-harden-deployments

#workflow:
  #done with feature branch, do pull request to main: test, collectstatic, build, deploy to stage
  #pull request successful (merged): test, collectstatic, build, deploy to prod

#notes:
  #commit to feature branch, then when making pull request, it takes the main.yaml at HEAD of the branch for Github Actions
    #on close and reopen pull request, it reuses that same main.yaml, without referring to newer main.yaml
  #not having $ in ${{}} would cause github actions to fail silently
  #rerunning a github action job will just reuse the main.yaml tied to it, not latest committed version
  #in yaml, there are "|" (pipe) and ">" in "run"
    #"|" respects nextlines and trailing spaces, i.e. you can run multiple consecutive commands by newline separation
    #">" will fold newlines to spaces, i.e. just makes an ultralong command easier to read and edit
  #env vars defined in github environments (project>settings>environments) introduces unwanted whitespace and newlines
    #at python, to remove all whitespace and newlines, do: ''.join(os.environ['YOUR_VAR'].split())
      #.split() removes start/any/end whitespace/newline, which can be more than 1, i.e. [substr0, substr1, substr2]
      #''.join() accepts iterable
    #this solution is easier than making sure pasted secrets/vars do not have newlines
  #parallel vs. sequence in jobs
    #parallel by default, i.e. independent
    #to make it sequential, use "needs: another_job_name" directly under job name, to make a job dependent on another
  #to run on pull request merged:
    #if: github.event.pull_request.merged == true

name: test, collectstatic, build, deploy

on:
  pull_request:
    #currently using "opened" only to run tests and nothing else
    #"closed" alone is bad, as closed covers both merged and not merged, so also check for: github.event.pull_request.merged
    #on merge, build and deploy to ECR, refer to this (not sure where to define in .yaml):
      #https://github.com/orgs/community/discussions/26724#discussioncomment-3253096
    types: [opened, closed]

jobs:
  #run this testing on pull request open and when merged
  run_tests:
    #make this false to skip this job, while we test other things
    if: false
    # if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.pull_request.merged == true) }}
    #specify environment to choose from git > settings > environments
    #https://stackoverflow.com/questions/66521958/how-to-access-environment-secrets-from-a-github-workflow
    environment: dev
    runs-on: ubuntu-latest
    container:
      image: python:latest
    #postgres, redis
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: voicewake
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: localhost
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379    
    #run django tests
    #always using dev
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5
      - name: Install Django dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Migrate and run tests
        env:
          DJANGO_SETTINGS_MODULE: voicewake.settings.dev
          SECRET_KEY: abc123
          ALLOWED_HOSTS: "*"
          DB_HOST: postgres
          DB_NAME: voicewake
          DB_USER: postgres
          DB_PASSWORD: localhost
          DB_PORT: 5432
          REDIS_ENDPOINT: redis://redis
          #tests don't use actual email, so leave AWS_SES empty
          AWS_SES_HOST:
          AWS_SES_SMTP_USER_NAME:
          AWS_SES_SMTP_PASSWORD:
          AWS_SES_FROM_EMAIL:
          AWS_SES_IAM_USER_NAME:
          #at github secrets
          #env vars defined in github environments (project>settings>environments) introduces unwanted whitespace and newlines
          #at python, to remove all whitespace and newlines, do: ''.join(os.environ['YOUR_VAR'].split())
          AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_S3_REGION_NAME: ${{ secrets.AWS_S3_REGION_NAME }}
          AWS_S3_CUSTOM_DOMAIN: ${{ secrets.AWS_S3_CUSTOM_DOMAIN }}
          AWS_S3_STATIC_BUCKET_NAME: ${{ secrets.AWS_S3_STATIC_BUCKET_NAME }}
          AWS_S3_MEDIA_BUCKET_NAME: ${{ secrets.AWS_S3_MEDIA_BUCKET_NAME }}
          AWS_S3_UGC_UNPROCESSED_BUCKET_NAME: ${{ secrets.AWS_S3_UGC_UNPROCESSED_BUCKET_NAME }}
          AWS_LAMBDA_ACCESS_KEY_ID: ${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }}
          AWS_LAMBDA_SECRET_ACCESS_KEY: ${{ secrets.AWS_LAMBDA_SECRET_ACCESS_KEY }}
          AWS_LAMBDA_REGION_NAME: ${{ secrets.AWS_LAMBDA_REGION_NAME }}
          AWS_LAMBDA_NORMALISE_FUNCTION_NAME: ${{ secrets.AWS_LAMBDA_NORMALISE_FUNCTION_NAME }}
        run: |
          python manage.py migrate
          python manage.py test voicewake.tests.test_apis.Core_TestCase
          python manage.py test voicewake.tests.test_apis.Users_TestCase
          python manage.py test voicewake.tests.test_apis.Core_NormaliseAudioClips_TestCase
          python manage.py test voicewake.tests.test_cronjobs.Core_TestCase
          python manage.py test voicewake.tests.test_cronjobs.Core_TransactionTestCase
  docker_build_tag_push_to_ecr:
    # needs: run_tests
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the AWS JWT
      contents: read    # This is required for actions/checkout
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.AWS_ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_ECR_REGION_NAME }}
      # - name: Login to AWS ECR
        # id: login-aws-ecr
        # uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, push to AWS ECR
        env:
          AWS_ECR_ACCOUNT_ID: ${{ secrets.AWS_ECR_ACCOUNT_ID }}
          AWS_ECR_REGION_NAME: ${{ secrets.AWS_ECR_REGION_NAME }}
          IMAGE_TAG: ${{ github.event.pull_request.number }}
        #github deprecated v1, so use "docker compose", not "docker-compose"
          #https://github.com/orgs/community/discussions/116610
        #github action runs at root of repository, not ./.github/workflows/*, i.e. no need to do ../../../
        # run: |
        #   echo "REGISTRY=${AWS_ECR_ACCOUNT_ID}.dkr.ecr.${AWS_ECR_REGION_NAME}.amazonaws.com" >> $GITHUB_ENV
        #   docker compose --file ../../../docker-compose-stage-prod.yaml up -d --no-deps --force-recreate --no-start --build
        #   docker tag "vw-django_celery_beat:${IMAGE_TAG}" "${REGISTRY}/vw-django_celery_beat:${IMAGE_TAG}"
        #   docker tag "vw-django_celery_worker:${IMAGE_TAG}" "${REGISTRY}/vw-django_celery_worker:${IMAGE_TAG}"
        #   docker tag "vw-django_gunicorn:${IMAGE_TAG}" "${REGISTRY}/vw-django_gunicorn:${IMAGE_TAG}"
        #   docker tag "vw-nginx:${IMAGE_TAG}" "${REGISTRY}/vw-nginx:${IMAGE_TAG}"
        #   docker tag "vw-redis:${IMAGE_TAG}" "${REGISTRY}/vw-redis:${IMAGE_TAG}"
        #   docker push "${REGISTRY}/vw-django_celery_beat:${IMAGE_TAG}"
        #   docker push "${REGISTRY}/vw-django_celery_worker:${IMAGE_TAG}"
        #   docker push "${REGISTRY}/vw-django_gunicorn:${IMAGE_TAG}"
        #   docker push "${REGISTRY}/vw-nginx:${IMAGE_TAG}"
        #   docker push "${REGISTRY}/vw-redis:${IMAGE_TAG}"
        run: |
          echo "REGISTRY=${AWS_ECR_ACCOUNT_ID}.dkr.ecr.${AWS_ECR_REGION_NAME}.amazonaws.com" >> $GITHUB_ENV
          docker compose --file docker-compose-stage-prod.yaml up -d --no-deps --force-recreate --no-start --build redis
          docker tag "vw-redis:${IMAGE_TAG}" "${REGISTRY}/vw-redis:${IMAGE_TAG}"
          docker push "${REGISTRY}/vw-redis:${IMAGE_TAG}"

  #ecr_rename_to_latest: todo?
    # if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}


  # collectstatic:
  # build_frontend:
  # deploy_stage:
  #   if: github.event.pull_request.merged == false
  #   #...
  # deploy_prod:
  #   if: github.event.pull_request.merged == true
  #   #...

















